apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: {{ stack_version }}
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
  podTemplate:
    spec:
      containers:
      - name: elasticsearch
        env:
        - name: ES_JAVA_OPTS
          value: -Xms750m -Xmx750m
        resources:
          requests:
            memory: 1.5Gi
          limits:
            memory: 1.5Gi
